### ISSUE TITLE
(README suggestion) Build instructions for Ubuntu/Mint

### ISSUE THREAD

**Issue by philpem** [travisgoodspeed/maskromtool#100]
This is mostly a "signpost" issue to get this onto the usual search engines.

The current version of Linux Mint (21.3) - and likely the Ubuntu version it's derived from - doesn't have a `qt6-charts-dev` metapackage. The apt-get command in the README will fail.

To install on these OSes, replace `qt6-charts-dev` with `libqt6charts6-dev`.

**Comment by travisgoodspeed** [comment]
Thanks for the signpost.  It's clear and concise, exactly as a signpost ought to be.

We'll keep this open until the instructions are corrected, either by adjusting the package name or by listing both.
