### ISSUE TITLE
Feature suggestion: copy multiple rows / grid placement

### ISSUE THREAD

**Issue by philpem** [travisgoodspeed/maskromtool#102]
In dealing with the chips I mentioned in #101, I realised I was placing a lot of columns and rows, with very similar spacing.

It would be useful to be able to select all the columns or rows (or both) in a certain area and copy them as a unit, then ideally adjust the positioning as a complete selection.

I think this would significantly speed up the time taken to mark the rows and columns, especially on chips like those in #101 which have eight identical banks of 16 or 32 lines running vertically down the screen, and hundreds of equally spaced horizontal rows running across and repeating downwards.

**Comment by travisgoodspeed** [comment]
Group selections (#105) should soon make this possible.  The rough workflow is that you will select some number of lines, duplicate them as a group, and then use your right mouse button to drag to the group to a new location.

**Comment by travisgoodspeed** [comment]
Groups can now be duplicated, but when sliding one line over another, you will destroy the lines of the unmoving line.  Until I figure out an efficient workaround, hit `V` or `M` to restore them.

**Comment by travisgoodspeed** [comment]
#106 will track the crossing line issue.
