### ISSUE TITLE
Feature suggestion: don't tile when zoomed out / fill with grey

### ISSUE THREAD

**Issue by philpem** [travisgoodspeed/maskromtool#104]
I've been working on a closely-cropped image of the ROM area of an on-screen display chip:

![image](https://github.com/travisgoodspeed/maskromtool/assets/845744/1331eeb8-0ddc-4486-be31-9dff512b7fa2)

The problem is, when I zoom out, this image tiles pretty much perfectly:

![image](https://github.com/travisgoodspeed/maskromtool/assets/845744/0b06dbff-b924-4581-881a-f85b5f2f39f6)

It would be nice if I could tell Mask ROM Tool to draw a plain background and only one copy of the source image, instead of tiling it.

To work around this, I added a border to the image I was working on.

**Comment by travisgoodspeed** [comment]
Currently we draw the background image as the background brush of the entire scene.  The right solution is probably to make a `QGraphicsItem` at `0,0` with the background image in it, and to make the background brush some lame color of grey.
