### ISSUE TITLE
Adjustable Line Colors

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/maskromtool#24]
The default color scheme works will on brightfield microscopy but is difficult to see in darkfield.  Close this issue when the colors are adjustable.

**Comment by philpem** [comment]
It would be nice to have selectable palettes, maybe from a menu dropdown.

My use case is I normally work in brightfield, but I've recently been working on some ROM dieshots which were imaged using a green interference filter. For that particular chip, GIF worked really well, but it made the green highlight and black gridlines hard to see.

It'd also be nice if the current colours could be shown in the status bar somewhere, perhaps as text or blocks in the assigned colours.

**Comment by travisgoodspeed** [comment]
Crosshair and selection colors are now adjustable.
