### ISSUE TITLE
Very large images fail to load.

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/maskromtool#34]
Very large files, those over one gigabyte, fail to load.  That's more than we need for many ROMs, but will become inconvenient at some point.

**Comment by DiscoStarslayer** [comment]
Maybe no longer valid? I've used maskromtool on a 2.27GB PNG quite successfully.

**Comment by travisgoodspeed** [comment]
Resolving as unreproducible.  Please reopen this if you have a file that can demonstrate the problem.
