### ISSUE TITLE
Compilation issue on Manjaro Linux

### ISSUE THREAD

**Issue by mladjo2505** [travisgoodspeed/maskromtool#56]
While attending the workshop on Balccon 2k23 I've have had a cmake issue on Manjaro Linux:
```CMake Error at /usr/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Charts" with
  any of the following names:

    Qt5ChartsConfig.cmake
    qt5charts-config.cmake

  Add the installation prefix of "Qt5Charts" to CMAKE_PREFIX_PATH or set
  "Qt5Charts_DIR" to a directory containing one of the above files.  If
  "Qt5Charts" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
```
even though I had the `qt6-charts` package installed.
What fixed it for me is removing  Qt5 from the find_package line in `CMakeLists.txt`:
```diff --git a/CMakeLists.txt b/CMakeLists.txt
index a2b517b..c4e6702 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -11,7 +11,7 @@ set(CMAKE_AUTORCC ON)
 set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_CXX_STANDARD_REQUIRED ON)
 
-find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Widgets LinguistTools Charts PrintSupport)
+find_package(QT NAMES Qt6 REQUIRED COMPONENTS Widgets LinguistTools Charts PrintSupport)
 find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Widgets LinguistTools Charts PrintSupport)
 
 # We currently only support English, so we define this file but we do
```
cc @travisgoodspeed I haven't had the time to do a clean system install/pull/build and add a list of packages on Manjaro needed to do a proper PR, so I just made this issue. If I get the time, I'll reference this issue in that PR. If you want/can test if above change doesn't break anything, just add it, no need for me to take the credit.
Cheers.

**Comment by travisgoodspeed** [comment]
Thanks for the bug report!  This was definitely a problem at the time of the Novi Sad workshop.

I think that this has since been fixed in #54.  Could you please give it a quick check, and confirm that this now works with the `master` branch and no alterations?

**Comment by mladjo2505** [comment]
Sorry, for the late reply, works

**Comment by travisgoodspeed** [comment]
Awesome!  Thanks for joining the workshop.
