### ISSUE TITLE
Selecting Image Error Windows

### ISSUE THREAD

**Issue by AluR526** [travisgoodspeed/maskromtool#7]
**Describe the bug**
I can run your Mask ROM Tool by compiling it through QT Creator.
However, when clicking File -> Open ROM I cannot select any .bmp image. It does not show the file in the file explorer.
You have to type the file name in manually to load up the image.

**To Reproduce**
1. Clicking File -> Open ROM

**Expected behavior**
You should be able to select/see the files in the file explorer

**Screenshots**
![Screenshot 2022-10-17 140549 (1)](https://user-images.githubusercontent.com/57150740/197407046-cdee872c-8761-4fe2-bf3b-c26906a4d65b.png)

**Desktop (please complete the following information):**
 - Windows 10

**Comment by travisgoodspeed** [comment]
Thanks for the report!  I'll get things compiling in a Windows VM and fix this right up.

**Comment by travisgoodspeed** [comment]
I think this was caused by bad parameter usage in the call to `QFileDialog::getOpenFileName`.  Please pull from `master` and rebuild, then confirm that the fix works.

**Comment by travisgoodspeed** [comment]
Confirmed fix in Windows 10.  Resolving.

![image](https://github.com/travisgoodspeed/maskromtool/assets/770671/0542e7bb-c9db-4cb9-8fce-655eb66fbc10)
