### ISSUE TITLE
Hex view crashes on very small ROM

### ISSUE THREAD

**Issue by shirriff** [travisgoodspeed/maskromtool#84]
If I put a 2 by 2 grid on the image and use the Hex View, it crashes repeatably in RomDecoderGato::gatorom with a segmentation fault, probably a null pointer.

I'm just filing this bug for reference; I don't have any interest in a fix for it.

[crash.txt](https://github.com/travisgoodspeed/maskromtool/files/13628893/crash.txt)

**Comment by travisgoodspeed** [comment]
Thanks for reporting this; it'll help make things more stable for the next fella.

Are you using the prebuilt release or compiling from source?
