### ISSUE TITLE
Auto-culling of Duplicate Rows

### ISSUE THREAD

**Issue by travisgoodspeed** [travisgoodspeed/maskromtool#97]
Sometimes a row is dropped in exactly the same place as another row.  This can't be meaningful so far as the decoding goes, so let's close this issue when those are automatically dropped during alignment.

**Comment by philpem** [comment]
This would be very useful - and also detecting rows which cross other rows (or the same for columns).

I've just had to throw away and re-start on a project because I'd stacked several rows on top of each other, and couldn't select any of them to delete them. When I tried to select them, the select tool seemed to do nothing.

**Comment by travisgoodspeed** [comment]
A group is selected like an individual line, but shift+D is needed to delete the group.  I'll also adjust that behavior.

**Comment by travisgoodspeed** [comment]
SHIFT+D is no longer needed.  The regular D command will delete group selections now.

Keeping this open until duplicates are automatically culled.

**Comment by travisgoodspeed** [comment]
This should no longer be a problem.  Among other changes:
1. `D` now erases either the focus item or the selection group.  Item is preferred and double-pressing kills both.
2. `SPACE` now places either a row or a column.
3. Placing a new line will delete the old line if they overlap.
4. Deleted items are now removed from the selection group, making it safe to delete both a line and the bits on that line in the GUI.

In the longer run, I'll probably remove the difference between the focused item and the selection group.  It's probably needed anyways for group movement and for duplicating groups.

**Comment by philpem** [comment]
I'll give that a shot, thanks.

How can I tell what the current "focus item" vs. "selection group" is? While I was selecting things by dragging boxes over them, I found it only seemed to work when I picked one item alone, and it turned green. I don't think I ever succeeded in selecting a group of items - or if I did, I couldn't tell that I had.

**Comment by travisgoodspeed** [comment]
I'll add coloring of the selection soon.  Until then, you can use `D` to delete the group and `^Z` to undo the change if the selection was wrong.
